# Generated by Django 2.0.6 on 2018-07-06 11:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('phoneNum', models.CharField(max_length=20)),
                ('postCode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('detailAddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('isCheck', models.BooleanField(default=True)),
                ('isOrder', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CategorieGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categorieId', models.CharField(max_length=20)),
                ('sort', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categoriegroups',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ChildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('sort', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=False, to='axf.CategorieGroup')),
            ],
            options={
                'db_table': 'childgroups',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='MainDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=20)),
                ('categoryName', models.CharField(max_length=40)),
                ('sort', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=200)),
                ('product1', models.CharField(max_length=20)),
                ('product2', models.CharField(max_length=20)),
                ('product3', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mainDescriptions',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('flag', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastTime', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=False, to='axf.Address')),
            ],
            options={
                'db_table': 'orders',
            },
            managers=[
                ('orders1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longName', models.CharField(max_length=150)),
                ('productId', models.CharField(max_length=20)),
                ('storeNums', models.CharField(max_length=20)),
                ('specifics', models.CharField(max_length=20)),
                ('sort', models.CharField(max_length=20)),
                ('marketPrice', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('categoryId', models.CharField(max_length=20)),
                ('childId', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=100)),
                ('brandId', models.CharField(max_length=20)),
                ('brandName', models.CharField(max_length=100)),
                ('safeDay', models.CharField(max_length=20)),
                ('safeUnit', models.CharField(max_length=20)),
                ('safeUnitDesc', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=150)),
                ('sort', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slideshows',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phoneNum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(default=None, max_length=20, null=True)),
                ('tokenValue', models.CharField(max_length=100)),
                ('headImg', models.CharField(max_length=200)),
                ('integral', models.IntegerField(default=0)),
                ('vipLevel', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastLoginTime', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=False, to='axf.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(on_delete=False, to='axf.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=False, to='axf.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=False, to='axf.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=False, to='axf.User'),
        ),
    ]
